### PR TITLE
Fix spelling mistakes

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by brianek** [comment]
Hi Tom:

We have a frew new changes we want to make to the site; mostly front
end (like our welcome page. Would you be open to doing this?

**Comment by tmcw** [comment]
@brianek possibly - I can help as much as time permits, and am aiming mostly to increase the approachability of codefordc projects, rather than doing lots of code tasks

**Comment by brianek** [comment]
okay.

**Comment by tmcw** [comment]
Mind merging this pull request ;)?

**Comment by stvnrlly** [comment]
This looks pretty straightforward, so I'm going to go ahead and merge.

**Pull request merged**
