### PR TITLE
Style/Layout Revisions

### PR DESCRIPTION
**Pull request by ParentJA**
@brianek Please review and merge this pull request. Thank you!

### CODE REVIEW

**Comment by brianek** [comment]
@DavidGinzberg A little help here on merging.

**Comment by brianek** [comment]
@ParentJA don't delete your branch just yet.

**Comment by DavidGinzberg** [comment]
Summary of PR from @ParentJA: @davidginzberg: hey guys, I reorganized some of the JS to handle some issues I saw: took variables off the global scope and encapsulated them into an Angular service, named functions for easy debugging, removed unused Angular controllers, implemented ui-router which is recognized as a big improvement over the native Angular ngRoute

parentja [13:44]
@davidginzberg: I reorganized some of the files: removed unused JS libraries, created folders to hold images and data files respectively

parentja [13:45]
@davidginzberg: the major changes included removing the Angular Material library and incorporating Bootstrap components and CSS into every part of the application

**Comment by brianek** [comment]
@DavidGinzberg i'm confused by the last post.

**Comment by DavidGinzberg** [comment]
@brianek are you in the Slack channel right now? My comment is just a snippet from that conversation that gives a little more detail on what was changed and why.

**Comment by brianek** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THANK YOU !!!!!!!!!!!!!!!!!!!!!!! @DavidGinzberg

**Pull request merged**
