### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by jmezetin**
Helper text section was missing from question displays and has be re-added.

### CODE REVIEW

**Comment by brianek** [comment]
it has conflicts. but wasnt the helper text already fixed?

**Comment by brianek** [comment]
didnt you fix it yesterday?

**Comment by brianek** [comment]
@jmezetin

**Comment by jmezetin** [comment]
Sorry, I was using the Github client and only wanted to update my repo. But it sent the pull request here. I closed this pull request just now, so feel free to ignore it.

**Pull request closed without merging**
