### PR TITLE
Adding in first round of translation

### PR DESCRIPTION
**Pull request by mkalish**
@brianek This is just the initial check in; unfortunately my spanish is not what it used to be so I was unsure where some of the translated text was suppose to go.  I'll be there Tuesday if you want to walk me through it and we can add translations for the rest of the site.

### CODE REVIEW

**Comment by brianek** [comment]
@mkalish The only thing that has been translated so far is the intro page and the FAQs section which is attached here. So basically, you are way ahead!!!! So thank you so much! . I forgot that Code for DC is on tuesday this week and I am in california till tuesday morning. Going further, where would I add the spanish translationsonce they are finished ? Did you fork the repo and have a specific repo for the spanish translation? Translation here: https://docs.google.com/document/d/1qm7xFhkEFZ3t6qL4iIooEz6drri_KoW0xjRl7est91c/edit

**Comment by mkalish** [comment]
I'm happy to keep adding the translations into the code as you get them and putting them into the google doc is good with me.  If you wanted to add them yourself, their is an english file locale-en.json for english and locale-es.json where English and Spanish versions can be put

**Comment by brianek** [comment]
Ok great. I'll let you know when new translations are available.

**Comment by brianek** [comment]
[Translation - Clean Slate DC (2).docx](https://github.com/codefordc/clean-slate/files/22023/Translation.-.Clean.Slate.DC.2.docx)
@mkalish: newtranslation is available.

**Pull request merged**
