### PR TITLE
Bootstrap and callouts

### PR DESCRIPTION
**Pull request by jimwebb**
Howdy! I've done a couple of things in these commits:
- Converted the layout and buttons to bootstrap (Nothing against, and apologies to, Angular Material Design, it's just that I don't know it and it was conflicting stylistically. Please feel free to revert.)
- Wired up the logic of the eligibility quiz such that it follows the scanned flowchart. Some of the later steps weren't hooked up properly.
- Added some definitions as seemed appropriate to the eligibility quiz, pulled from the definitions word document. Also added a "callout" style for rendering them on the quiz steps.
- Stubbed out text for the "eligible" and "ineligible" pages.

Thanks!

### CODE REVIEW

**Comment by jimwebb** [comment]
Oops. It looks like due to mis-communication that Justin at the Hack Night tonight may have overlapped a bunch of this work. I also suspect I've breached several rules of etiquette by removing Angular Material Design in favor of Bootstrap, and for not making commits atomic enough that you can pick and choose what you wanted. I'm new at this! My apologies.

**Comment by brianek** [comment]
great job! Any way you can add in a screenshot of these changes?

**Comment by jimwebb** [comment]
Sure:

home

eligibility

**Comment by brianek** [comment]
thanks!!!

**Comment by jimwebb** [comment]
This is obsolete. Closing.

**Pull request closed without merging**
