### PR TITLE
Applied Bootstrap styling.

### PR DESCRIPTION
**Pull request by ParentJA**
@brianek OK, test this and tell me what you think. If you like it, I can apply it to FAQs too. I have the behavior so that multiple tabs can be open at once.

### CODE REVIEW

**Comment by brianek** [comment]
It looks great. But the links are not working (i.e. when I click on the word, there is no response). @ParentJA

**Comment by ParentJA** [comment]
Are you sure? I just pulled up the site on my iPhone and it's working fine. Also working fine on my laptop.

**Comment by brianek** [comment]
I tried again and its not working; but it could be that my internet connection is really poor ( I am at a coffee shop) . I am moving locations and will try again in 15/20 minutes.

**Comment by ParentJA** [comment]
Here's screenshot from phone.

**Comment by brianek** [comment]
Yes it works. Sorry for the lateness; I got sucked into a board meeting.

**Comment by brianek** [comment]
I also updated another page so just an fyi to download latest files.

**Comment by brianek** [comment]
And yes, we would like the same effect on the faqs page if it is not too much trouble @ParentJA

**Pull request merged**
