### PR TITLE
Created Results Page

### PR DESCRIPTION
**Pull request by ave-llan**
I made a separate results page and a new ResultsController, moved the question/answer history into a table, and added print, e-mail, and start over buttons.

I ran out of time to work on this today but wanted to send this out in case someone has time to start styling the page.  Currently the table has no CSS applied but the markup is there. 

The e-mail button doesn't work yet.

The print button works, but just prints the whole page, and we might want to write css for the printer to remove things like the buttons (or we could do this with javascript).

Finally, I wanted to note that I am now storing the question/answer history in a global variable outside of EligibilityWizardController so that ResultsController can see it.  This works for now, but it would be better to create a custom Angular Service to pass the data between controllers.

### CODE REVIEW

**Comment by ave-llan** [comment]
Here is the new results page. Not so pretty right now, but ready to be styled by someone!

screen shot 2015-05-07 at 4 02 52 pm

**Comment by brianek** [comment]
Thank you!

**Comment by cweems** [comment]
@brianek @jrleszcz would you guys mind holding off on this? The PR I'm about to submit addresses these issues in addition to routing, but I'm worried about serious merge conflicts.

**Comment by cweems** [comment]
Just submitted #33 ! @jrleszcz huge apologies for cutting in line, but I think it's going to be easier to do the routing changes first and then negotiate the second controller.

**Comment by brianek** [comment]
So before i accept this merge, can I just confirm that it will include @cweems changes and the above changes references by @jrleszcz jrleszcz?

**Comment by cweems** [comment]
@brianek we'll need to resolve this merge conflict manually. I think my PR has more fundamental changes which is why I'm recommending we do it first. If you'd prefer, I can create a new branch and merge these two and create a new pull requested where they are reconciled.

**Comment by ave-llan** [comment]
I agree you should accept #33  first because it looks like quite a bit more was changed than in #32.  The new design looks great!

**Comment by brianek** [comment]
yes that would be great. I love the changes you made. But the structure of the results page above (print vs. email results) is great.  But we would need to first discuss further jrieszcz comments: "Finally, I wanted to note that I am now storing the question/answer history in a global variable outside of EligibilityWizardController so that ResultsController can see it. This works for now, but it would be better to create a custom Angular Service to pass the data between controllers." Do you have an opinion on this? What are the pros and cons? We want to make an app that is going to be reliable for people and available on any computer or any phone.

**Comment by brianek** [comment]
ok

**Comment by cweems** [comment]
@jrleszcz thanks! Happy to move your stuff in there in another PR, although you may want to take that on yourself so that you can see what I've change. Big :+1: on the new structure for the questions – lots of good stuff there that is going to make this more scalable.

@brianek agree that we may wish to create an angular service to accommodate this. But for the moment its really a code cleanliness issue. Not going to change how this works on other computers.

**Comment by cweems** [comment]
@jrleszcz another issue to consider for the results page is how to persist the data if the user refreshes. We could do this with a cookie, but I'm a bit worried about user privacy in the instance where someone uses this from a public computer. 

Creating an actual accounts framework would be the most comprehensive way to address this, but it also has the tradeoff that users would have to sign up. Besides being an automatic dropoff point, I think folks could be really nervous about providing any potentially personal information.

The good news is that even if a user refreshes mid-process, they will still end up at the correct eligibility state. They would just loose a portion of their response history. This might be a bigger issue to talk about at the next meetup, but totally open to suggestions.

In the meantime, I'm planning on implementing gulp to automate our build process (i.e. comment remove and minification for distribution). I'll be sure to document the gulp commands I create in the readme!

**Comment by brianek** [comment]
it my be worth it to hold off on the cookies or the log-in until we talk to
the lawyers. We are going to be tracking the emails that are submitted and
those who visit the site so we can measure how many people complete the
assessments and then go onto to get a lawyer to seal their record.

**Comment by brianek** [comment]
The rep for the lawyer will be at code for dc next week

**Comment by ave-llan** [comment]
Hey @cweems, have you started to automate the build process like you mentioned above?  If not, I was wondering if you could walk through that with me as it's something I've been meaning to learn.

**Comment by brianek** [comment]
also can you explain more about the automate process. 
After we demo this app in June, we are considering how we can build an app that (when given a list of crimes) can automatically go through the questions and assess eligibility with one click of a button.

**Comment by stvnrlly** [comment]
@brianek The automation being discussed here is different than that; it's about using a tool like [gulp](https://github.com/gulpjs/gulp) to simplify some development tasks.

**Comment by brianek** [comment]
ok thats what I was thinking.

**Comment by cweems** [comment]
@jrleszcz happy to! I was traveling this weekend but maybe let's plan on talking during the meetup.

**Comment by brianek** [comment]
Just fyi that we might host a hacknight specifically to update all of the
content into the site either thursday night or sunday afternoon/night.
Baked goods, wine or snacks may make an appearance based on the # of
attendees.

Let me know if either of these dates work better for you.
On Wed, May 13, 2015 at 12:44 PM, John Leszczynski <notifications@github.com

**Pull request closed without merging**
