### PR TITLE
Added summary of answers at end (issue #25) & refactored functionality

### PR DESCRIPTION
**Pull request by ave-llan**
Now when the user reaches an endpoint in the wizard, they get a summary of all of the questions with the answers they gave.  It is easy to change the formatting in "views/eligibility-checker.html" to make this look nicer. 
screen shot 2015-04-30 at 7 47 27 am

I moved the eligibility flow chart logic and data out of the DOM and into app.js itself. Questions can all be edited in one place now, and it would be easy to add new questions or edit the flow if needed. Maybe next I should move this into a separate json file?

The list of ineligible misdemeanors/felonies was only on step 2 before, but I also added it to step 8 which asks the same question.

### CODE REVIEW

**Comment by brianek** [comment]
Hi:

I just want to say thank you!!!!

**Comment by brianek** [comment]
What are the benefits of moving this into a separate json file?

**Comment by brianek** [comment]
Drawbacks?

**Comment by brianek** [comment]
GREATTTTT JOBBBB!!!!!

**Comment by ave-llan** [comment]
Happy to help!  

I don't think there are any tangible benefits to moving questions and the flow chart instructions out of app.js and into a separate .json file besides making the code 'cleaner' so it probably doesn't really matter, though maybe someone more knowledgable than me can weigh in.

**Comment by brianek** [comment]
if by cleaner, you mean better for the organization who will inherit this code once the project is finished than i would say yes do it. As an alternative, I, as a non-techie, have found that the most helpful part of code that  are the comments. So if you could add comments(for example, where new content should be entered) that would be super helpful!

Best,
Briane

**Comment by jmezetin** [comment]
Hey Briane, 

Are you able to accept the pull the requests into the main branch so it can be easier for others to see the updated version?

**Comment by ave-llan** [comment]
By the way, I wasn't aware of Pull Request #26 when I was working on this— are you planning to merge it into the project? 

I am kind of new to github so didn't know to look out for other pull requests, but I just noticed it and we would have to reconcile this one with #26.

**Comment by brianek** [comment]
Great, I will ask JimWebb (who submitted #26) to reconcile them.

**Comment by brianek** [comment]
Sure. For #25 and #28 right?

**Comment by brianek** [comment]
Merge accepted!

**Comment by cweems** [comment]
@districtinroads fantastic work on refactoring this! Going to take a pass at making routing work (fixing the back button issue) later tonight if that's ok!

**Comment by brianek** [comment]
Awesome @charile Weems!

**Comment by cweems** [comment]
@brianek would you mind adding me as a collaborator for the project when you have a chance so that I can push up my changes to a new branch?

**Comment by brianek** [comment]
done

**Comment by cweems** [comment]
@brianek Hey sorry to bother you, but would you mind checking again? Still getting permission denied and not seeing myself here: https://github.com/codefordc/expungement-dc/network/members

**Comment by brianek** [comment]
Anyway it is in your spam? It is saying that I sent the invitation; see screen shot below. You are not bugging me at all.  Feel free to ask questions. I am new to github so there might be something I am missing. I will look more into it.

**Comment by stvnrlly** [comment]
@cweems That screen shows all of the project's forks, not the team members. You don't need any special permission to fork and submit a pull request, if you want to go that route. 

Here's what you'd need:
- [Forking](https://help.github.com/articles/fork-a-repo/)
- [Pull Requests](https://help.github.com/articles/using-pull-requests/)

**Comment by brianek** [comment]
Great: yes please follow stvnrlly's comments. You can fork the repo and
submit a pull request after you are done! and also provide a screenshot of
your work.

**Comment by stvnrlly** [comment]
(Also, @cweems, I'm available on the Code for DC Slack if you have further questions.)

**Comment by cweems** [comment]
@brianek sweet thanks! You were right - the invite went straight to my info box.

@stvnrlly good to know! It's been ages since I've worked on projects outside of my organization so this is a good refresher.

**Comment by ave-llan** [comment]
Hey @cweems, just a heads up that I had to change the functionality a bit when I moved the eligibility-flow into a separate json file in pull request #29.  

It is actually much simpler now I think, and you would probably want to work from that version so there are no conflicts.

**Comment by brianek** [comment]
@districtinroads One additional feature that we will add to the endpoint is the ability to print/email the result and then move onto another question. So we will prompt the individual to first print/email their results and then to move onto the next optional stage of questions.

**Comment by ave-llan** [comment]
@brianek sure, it shouldn't be too difficult to add those features.  I will try to do the print/email option tomorrow, but I will need to see what the next round of 'optional' questions are like before doing that section.

**Comment by brianek** [comment]
Great.

Basically we will end up having 5 wizards based on the categories indicated
in the attached picture (A, B, C, D, E). The hope is that we will either at
the front end give them the option of selecting multiple wizards, or once
they finish a wizard we will prompt them to go through another wizard. I'm
leaning toward the latter. Let me know if you have an opinion on that
ux/design wise.

**Comment by brianek** [comment]
@cweems. Thanks. I have created a roadmap of the next steps for this project if you are interested. Please note your interest so that i am knowledgeable about who is working on what: https://docs.google.com/presentation/d/1vCgDUQFLVqBx18dExyK01PfNHnLSI6aCoobV-h2Z4X8/edit?usp=sharing

**Pull request merged**
