### PR TITLE
End state abstraction

### PR DESCRIPTION
**Pull request by ave-llan**
Updated format for json end states to allow for many endstates.  From the new README, this is how endStates should be formatted:

This is an endState object:

```
"eligible":{
        "eligiblityText":"This offense is likely eligible for expungement.",
        "helperText":"...this is what you should do next in this case..."
        }
```

And this is how it would look:
screen shot 2015-05-14 at 11 30 55 am

So if you want a different message for a certain endState, just make a new endState. 

This involved changing quite a bit of the `EligibilityWizardController` because before the endState names were hardwired in, and it depended on question names being numbers.   Now any valid string should work as a question or endState name.

### CODE REVIEW

**Comment by ave-llan** [comment]
Unfortunately the endState Glyphicons depended on hardwired endState names, so for now I commented them out.  We could add this back in as a property to the endState objects. 

Also the progress bar depended on question names being numbers, so it doesn't work right now.  This should actually be fun to fix because we can do a little path finding through the json.  I will work on it next.

**Comment by brianek** [comment]
Yeah I really like the glyphicons and the progress bar

**Comment by brianek** [comment]
Before I merge this request, I was wondering do you think if we did it the way jim webb was proposing that there would be a conflict with the glyphicons and the progress bar?

**Comment by ave-llan** [comment]
(I think @cweems should look over my changes before this is merged. )

The issue with the glyphicons is a simple fix -- I just ran out of time yesterday.  The problem is that they were coded to work specifically with the three eligibility states we had before, but if we want them to work with any possible endState (and from the meeting on Wednesday, it sounds like there might be a lot), we have to abstract that functionality a bit.  It would be the same issue with any format for the JSON I think. 

I'll try to push a fix to this merge request in the next few hours that will add them back in. It will probably involve adding one more field to the json for the endstates, indicating which glyphicon we want to show (currently it is just a checkmark, a clock, or an 'X' I think).

**Comment by brianek** [comment]
got it

**Comment by ave-llan** [comment]
Icons are back, now you specify whatever icon you want to use in the json in a field on the endState objects. 

Excerpt from the new README:

```
      "eligible":{
        "eligiblityText":"This offense is likely eligible for expungement.",
        "icon":"glyphicon glyphicon-ok-circle",
        "helperText":"...this is what you should do next in this case..."
        }
```

`"icon"` = name of a [Bootstrap glyphicon](http://getbootstrap.com/components/#glyphicons) to be displayed on results page.  If no icon is desired, this can be an empty string `"icon":""`.

**Comment by brianek** [comment]
thxs. Give me a heads up when I should merge.

On Fri, May 15, 2015 at 10:22 AM, John Leszczynski <notifications@github.com

**Comment by ave-llan** [comment]
And now the progress bar is back! It still depends on question names being numbers, so for flexibility down the road, I would like to make it work even if that is not the case.  But for now, it works great!

screen shot 2015-05-15 at 10 35 11 am

**Comment by ave-llan** [comment]
@brianek it is ready to merge on my end.  

Ideally I would still like someone to look over the code, but I have tested everything, and it is working well.  I guess if you want to merge it now so that people can see the new JSON format, that probably makes sense.  Then if @cweems finds anything he wants to change we can do another pull request.

**Comment by brianek** [comment]
ok Thanks!!!!

On Fri, May 15, 2015 at 10:52 AM, John Leszczynski <notifications@github.com

**Comment by cweems** [comment]
@jrleszcz @brianek great work! going to dive into the code myself but looks good so far.

**Pull request merged**
