### PR TITLE
Move eligibility flow into separate json file

### PR DESCRIPTION
**Pull request by ave-llan**
I created a separate json file named eligibility-flow.json which anyone can change to edit the question text or answer text.  

I tried to make the format flexible.  Right now, all the questions have only two answers, but now it would be easy to add multiple answers if the need arises later on.  I've also left space for "helperText" where we can add definitions to explain the legal terms.  

(Everything still looks the same, so I am not adding a screenshot.  This just changed the functionality.)

### CODE REVIEW

**Comment by ave-llan** [comment]
Here is an example of the format from the new json file.

questionText = question that will be displayed for the user 
answerText = words that will be displayed on the buttons
next = which question should the user see next if they click this answer?
helperText = definitions or explanations of confusing wording in the question (currently empty, we need to add it)

```
   "question0":{  
      "questionText":"Do you have a case pending?",
      "answers":[  
         {  
            "answerText":"Yes",
            "next":"ineligible at this time"
         },
         {  
            "answerText":"No",
            "next":"question1"
         }
      ],
      "helperText":[  

      ]
   },

   "question1":{  
      "questionText":"Are you sealing a conviction or a non-conviction?",
      "answers":[  
         {  
            "answerText":"Conviction",
            "next":"question2"
         },
         {  
            "answerText":"Non-conviction",
            "next":"question5"
         }
      ],
      "helperText":[  

      ]
   },
```

**Comment by ave-llan** [comment]
If there is helperText for the question, it now displays below the buttons like this:

screen shot 2015-05-05 at 11 06 41 am

I am going to put in the definitions that @jimwebb added in #26

**Comment by ave-llan** [comment]
Finally, I added a brief explanation of the formatting of the eligibility-flow.json to the README so that non-technical people can be comfortable working with that file.  If my explanation is not clear, let me know!  Here is what it will look like in the README:

screen shot 2015-05-05 at 12 05 42 pm

I think I'm done adding commits so unless you have a request, it is ready to merge!

**Comment by jmezetin** [comment]
For some reason, the updated site is not working from the github account

**Comment by ave-llan** [comment]
It's because of the project name change to "clean-slate"
Try this: http://codefordc.github.io/clean-slate

**Comment by brianek** [comment]
steven do u think my name change affected his pull?

**Comment by brianek** [comment]
right. what should i do to fix it?

**Comment by ave-llan** [comment]
I think you can just edit the link at the top of the page and it should work.  On my fork of the project I was able to do that; there should be an 'edit' button next to the link.

**Comment by brianek** [comment]
is the updated site working for you now?

**Comment by stvnrlly** [comment]
@brianek Just edited it; this didn't affect the pull, just the description at the top of [the main page](https://github.com/codefordc/clean-slate).

**Comment by brianek** [comment]
thank you!!!

**Comment by brianek** [comment]
Thanks. I have created a roadmap of the next steps for this project if you are interested. Please note your interest so that i am knowledgeable about who is working on what: https://docs.google.com/presentation/d/1vCgDUQFLVqBx18dExyK01PfNHnLSI6aCoobV-h2Z4X8/edit?usp=sharing

**Pull request merged**
