### PR TITLE
Added link to app -Updated Read-Me

### PR DESCRIPTION
**Pull request by brianek**
Updated Read-Me

### CODE REVIEW

**Comment by stvnrlly** [comment]
I'd recommend against removing installation instructions, no matter how basic they are. Instead, the `git clone` should be updated to point to this repo.

**Comment by brianek** [comment]
So I removed at the instruction of Ryan. The installation instructions were incorrect and pointed to wrong thing.

**Comment by stvnrlly** [comment]
Yep, that's fine. If we correct that `git clone` link instead of deleting the instructions, I think this will be ready to be merged.

**Comment by brianek** [comment]
Okay. I'm pretty new to using this so I will do so, once I have figured out
what link to put.

**Comment by stvnrlly** [comment]
The link is https://github.com/codefordc/expungement-dc.git (you can always find it in the right sidebar of the repository's main page).

To be clear, this isn't a Github-level standard, but more a Code for DC thing. We're expecting that people checking out our projects may be relatively inexperienced, so we're leaning towards keeping documentation that may be obvious to more experienced Github users.

I'm also going to revise my suggestion. Since the goal is setting up a repo for development purposes, the instructions should be for forking and cloning rather than just forking. Here's what we say in another repo:

```
First, make sure that you have [`git`](http://git-scm.com/downloads) on your computer. Create your own [fork](https://guides.github.com/activities/forking/) of the repository, then clone it to your computer:

    git clone git@github.com:[YOUR GITHUB NAME]/codefordc-2.0.git

You can work on the `master` branch (which is the default), but it's preferable to set up a new branch if you're working on a specific feature:

    git checkout -b [NEW BRANCH NAME]
```

I think that would work well here, too, with `expungement-dc` swapped in for `codefordc-2.0`.

**Comment by brianek** [comment]
Ok i'm going to try and do it right now.

**Comment by stvnrlly** [comment]
Oops, I forgot to come back to this. Thanks, @brianek, this looks good, and thank you for putting up with my nitpicking.

**Comment by brianek** [comment]
no problem I don;t mind doing it i just needed help with how to do it.

**Pull request merged**
