### PR TITLE
Added behavior to make the definitions load from a data file.

### PR DESCRIPTION
**Pull request by ParentJA**
Added functionality to show truncated definition that shows full text on click.

### CODE REVIEW

**Comment by ParentJA** [comment]
@brianek I updated the definitions page so that the definitions are collapsed by default, with truncated text showing. This makes it easier for mobile users. Clicking on a title expands the text to show the full definition. Clicking again truncates it again. This needs some styling work, but the behavior is there.

**Comment by ParentJA** [comment]
@brianek The biggest change to the previous files is that I extracted the content into a data file, just like the eligibility questions are. This branch is safe to merge, so feel free to do so at your convenience (or give me the go-ahead and I'll do it). Remember, you can test the functionality by pulling the branch on your local machine, running the local server, and visiting the "Definitions" part of the site.

**Comment by brianek** [comment]
It did work. I'm torn between your design and the design found here: http://jqueryui.com/accordion/. The design you implemented, is this code easier to implement? And lastly, we would love this implemented in the FAQs section.

**Comment by ParentJA** [comment]
@brianek Yes, we can definitely style the list to look like jQuery UI one. For the first step, I just wanted to get the functionality working. What do you think about this example: http://getbootstrap.com/javascript/#collapse-example-accordion? That uses Bootstrap, which is the front-end design framework we are currently using. I would like to limit the number of libraries we're bringing in to the project.

**Comment by brianek** [comment]
@ParentJA yes I like the boorstrap!!! I am not sure it was responsive though. I tried to view it via developer tools and  it didnt come off as responsive. But I did not try it on my phone.

**Comment by ParentJA** [comment]
@brianek Yes, Bootstrap is responsive. I'll mock something up and show you soon.

**Comment by brianek** [comment]
@ParentJA okay great!!!!

**Pull request merged**
