### PR TITLE
Updated JSON document

### PR DESCRIPTION
**Pull request by jmezetin**
Added Section e: Non-conviction and convictions 
Added Definition for swearing under oath
Added non-convictions and convictions button

### CODE REVIEW

**Comment by ave-llan** [comment]
Nice work!  I was just looking at all the new additions and noticed there is at least one capitalization inconsistency between the name of an endState object and the 'next' link in the questions to that endState. 

Question 501 links to `ineligiblePC` but the endState is actually named `IneligiblePC`.  

The update I did that makes the progress bar work is currently not very forgiving of this, and you can see on your [gh-pages](http://jmezetin.github.io/clean-slate) that this will cause an error:
screen shot 2015-05-30 at 7 09 03 pm

Also your placeholder `"next":"GOTO??????"` will cause an error.

**Comment by brianek** [comment]
@jmezetin yes the progress bar is very sensitive. But if you change the capitilization it should work. Can you change that and resubmit the pull request when you are able to?

**Comment by jmezetin** [comment]
I fixed the document replacing the "Goto???" and went through a couple times to ensure the cases are correct for all the end states and next questions, and validating the JSON. But am still having trouble with the file. 

If you have any tips of how to find the error, let me know.

**Comment by ave-llan** [comment]
@jmezetin I am working on a change to the function that finds the tree height (used for the progress bar), this will be more forgiving if there is an error in the JSON. It will also log that error so we can fix it.

It looks like 540 links to 544 and 544 does not exist.

**Comment by ave-llan** [comment]
PR #58 will allow this to work while also logging the name of the missing state in the console so it is easy to find.

**Comment by brianek** [comment]
Thanks to both of you!!! Great teamwork!!!

**Pull request merged**
