### PR TITLE
Updated Home page and added questions into json

### PR DESCRIPTION
**Pull request by jmezetin**
I added the home page that we attempted to do two code-for-dc meetups ago.

I also added some of the other question flows from Shannon's sealing chart document into the json file in the same order as the document, for each of the other paths. 

An initial question or set of questions is needed to direct the user to the first question for any of the paths.

Also, the final page or results in the various paths will need to be set-up and have the correct text.

### CODE REVIEW

**Comment by brianek** [comment]
I did not understand the last part "the final page or results in the
various paths will need to be set-up and have the correct text." Feel free
to send me more info or a screenshot of your progress.

**Comment by stvnrlly** [comment]
@brianek Since @jmezetin used the `gh-pages` branch of the fork, you can see the forked version of the site here: https://jmezetin.github.io/clean-slate/#/

**Comment by brianek** [comment]
@stvnrlly Thank you!!!

**Comment by stvnrlly** [comment]
I think what he's saying that this adds information about the full meta-process, including checking a criminal record and submitting paperwork, but doesn't fully implement the multi-path wizard or the final result/check another record ending page, both of which were discussed yesterday.

Those two things aren't entirely necessary to complete the full flow from the sealing chart, but I think that it would make sense to incorporate those here before this pull request is merged. If not, then that should follow shortly after this, since the questions are a little confusing. There are also some places where text needs to be filled in, particularly for definitions.

I'm also wondering why Step 2 is checking your criminal record. Shouldn't that be Step 1?

**Comment by brianek** [comment]
Yes, those would need to be incorporated. Agree with stvrlly, that the acquiring of the criminal record is the first step. Also @jmezetin -sorry to ask this but would you be willing to make the first page look more like this in regards to layout: http://www.mrelief.com/. I still want the steps layed out but they should be horizontal if possible. I am working on a revised road map so that everyone is on the same page.

**Pull request closed without merging**
